app/maestros/sede/models.py
from app.database import mysql

#CREATE
def crear_sede(NombreSede, Direccion, Telefono, Director, ActiveCampus):
    # Cursor para la ejecución
    cur = mysql.connection.cursor()  # Siempre va este
    # QUERY de Insert
    sQuery = '''INSERT INTO sede (Nombre_sede, Direccion, Telefono, Director, Activo) 
      VALUES(%s, %s, %s, %s, %s, %s)'''
    #print(sQuery)
    # Ejecucion de la Sentencia
    cur.execute(sQuery, (NombreSede, Direccion, Telefono, Director, ActiveCampus))
    
    mysql.connection.commit()

    # Cerramos el cursor
    cur.close() 
    
#READ
def datos_sede():
    cur = mysql.connection.cursor()
    sQuery = '''SELECT * FROM bd_escuela.sede '''.format()
    #print(sQuery)
    cur.execute(sQuery)
    row = cur.fetchall()

    # Ejecucion de la Sentencia
    cur.execute(sQuery)
    mysql.connection.commit()

    # Cerramos el cursor
    cur.close()

    return row

def ver_sede(codigo):
    cur = mysql.connection.cursor()
    sQuery = '''SELECT * FROM bd_escuela.sede Where IdSede like '%{}%' '''.format(codigo)
    #print(sQuery)
    cur.execute(sQuery)
    row = cur.fetchone()

    # Ejecucion de la Sentencia
    cur.execute(sQuery)
    mysql.connection.commit()

    # Cerramos el cursor
    cur.close()

    return row

#model para traer los datos de las sedes para seleccionar
def validar_sede(idsede):
    cur = mysql.connection.cursor()
    sQuery = "SELECT * FROM bd_escuela.sede where idSede='{}' ".format(idsede,)
    #print(sQuery)
    cur.execute(sQuery)
    row = cur.fetchall()

    # Ejecucion de la Sentencia
    cur.execute(sQuery)
    mysql.connection.commit()

    # Cerramos el cursor
    cur.close()

    return row

def actualizar_sede(NombreSede, Direccion, Telefono, Director, ActiveCampus, IdSede):
    # Cursor para la ejecución
    cur = mysql.connection.cursor()
    # QUERY de UPDATE
    # Ejecucion de la Sentencia
    cur.execute('''UPDATE bd_escuela.sede SET Sede=%s, Activo=%s, Tiposede=%s
     WHERE Idsede=%s ''', (NombreSede, Direccion, Telefono, Director, ActiveCampus, IdSede))
    mysql.connection.commit()

    # Cerramos el cursor
    cur.close()

#DELETE
def eliminar_sede(Documento):
    # Cursor para la ejecución
    cur = mysql.connection.cursor()
    # QUERY de UPDATE
    # Ejecucion de la Sentencia
    cur.execute('''DELETE from bd_escuela.sede WHERE Idsede=%s ''', (Documento,))
    mysql.connection.commit()

    # Cerramos el cursor
    cur.close()

app/maestros/sede/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField,DateField, validators
from wtforms.validators import DataRequired, Email, Length

class Campus(FlaskForm):
    NombreSede = StringField('Nombre Sede', [
                            validators.DataRequired(message='El nombre de la sede es obligatorio'),
                            validators.Length(
                            min=10,
                            max=60,
                            message='Minimo 10 caracteres máximo 60')])
    Direccion = StringField('Direccion', validators=[
                            DataRequired(
                            message='La dirección es obligatoria'),
                            Length(
                            max=60
                            )])
    Telefono = StringField('Teléfono', validators=[
                            DataRequired(
                            message='El teléfono es obligatorio'
                            ),
                            Length(
                            max=10,
                            message='Debe ser de máximo 10 digitos'
                           )])
    Director = StringField('Director', [
                            validators.DataRequired(
                            message='El director es obligatorio'),
                            validators.Length(
                            min=3,
                            max=60,
                            message='Minimo 3 caracteres máximo 60'),
                            ])
    ActiveCampus = StringField('Estado: ', validators=[
                            DataRequired(
                            message='El estado es obligatorio'
                            )])
    Submit = SubmitField('Registrar')

app/maestros/sede/__init__.py
from flask import Blueprint

sede = Blueprint('sede',__name__, template_folder='templates',url_prefix='/sede')

from . import routes

app/maestros/sede/routes.py
from flask import render_template, request, redirect, url_for, flash, session
from .forms import Campus
from . import models
from werkzeug.security import generate_password_hash, check_password_hash
from . import sede

#Ruta muestra la tabla de sedes
@sede.route('/', methods=["GET", "POST"])
def list_sede():
    if 'documento' in session:
        row = models.datos_sede()
        return render_template('listCampus.html', Datostabla=row)
    else:
        return redirect(url_for('inicio.login'))

#Ruta para crear registros
@sede.route('/crear', methods=["GET", "POST"])
def createCampus():
    if 'documento' in session:
        if session['privilegio'] != 'C':
            form = Campus()
            sedes = models.datos_sede()
            if request.method == 'POST':
                if form.validate_on_submit():
                    IdSede = form.IdSede.data
                    NombreSede = form.NombreSede.data
                    Direccion = form.Direccion.data
                    Telefono = form.Telefono.data
                    Director = form.Genero.data
                    Rol = 'C'
                    ActiveCampus = form.ActiveCampus.data
                    # Validar que no exista el registro persona
                    row = models.validar_sede(IdSede)

                    if row == None:
                        # Se crea un nuevo registro en persona
                        models.crear_sede(NombreSede, Direccion, Telefono, Director,  ActiveCampus)
                        flash('Registro Creado Exitosamente', 'success')
                    else:
                        flash('El Registro ya existe', 'success')

                return redirect(url_for('sede.list_sede'))
            else:
                return render_template('createCampus.html', form=form, sedes=sedes)
        else:
            flash('No dispone de privilegios para crear registros', 'success')
            return redirect(url_for('inicio.home'))
    else:
        return redirect(url_for('inicio.login'))
    
#Ruta para consultar registros
@sede.route('/see/<int:codigo>', methods=["GET", "POST"])
def see_Campus(codigo):
    if 'documento' in session:
            form = Campus()
            row = models.ver_sede(codigo)
            return render_template('seeCampus.html', form=form, Datoregistro=row)
    else:
        return redirect(url_for('inicio.login'))

#Ruta para editar registros
@sede.route('/edit/<int:codigo>', methods=["GET", "POST"])
def editCampus(codigo):
    if 'documento' in session:
            if session['privilegio'] != 'C':
                form = Campus()
                datos=models.ver_sede(codigo)
                datoscombo1 = models.validar_sede()
                if request.method == 'POST':
                    if form.validate_on_submit():
                        IdSede = form.IdSede.data
                        NombreSede = form.NombreSede.data
                        Direccion = form.Direccion.data
                        Telefono = form.Telefono.data
                        Director = form.Genero.data
                        ActiveCampus = form.ActiveCampus.data
                        # Validar que no exista el registro persona
                        models.actualizar_sede(NombreSede, Direccion, Telefono, Director, ActiveCampus)
                        flash('Registro Actualizado Exitosamente', 'success')
                        return redirect(url_for('sede.list_sede'))
                    else:
                        return render_template('editCampus.html', form=form, Datoregistro=datos)
                else:
                    return render_template('editCampus.html', form=form, Datoregistro=datos)
            else:
                flash('No dispone de privilegios para editar registros', 'success')
                return render_template('seeCampus.html', form=form, Datoregistro=datos)
    else:
        return redirect(url_for('inicio.login'))
    
#Ruta para eliminar registros
@sede.route('/delete/<int:codigo>', methods=["GET", "POST"])
def deleteCampus(codigo):
    if 'documento' in session:
            if session['privilegio'] != 'C':
                models.eliminar_sede(codigo)
                flash('Registro Eliminado Exitosamente', 'success')
            else:
                flash('No dispone de privilegios para eliminar registros', 'success')
            return redirect(url_for('sede.list_sede'))  
    else:
        return redirect(url_for('inicio.login'))

app/maestros/sede/templates/createCampus.html
{% extends "base_template.html" %}

{% block title %}Registrar Sede{% endblock %}

{% block content %}
<div class="container pt-4">
  {% with messages=get_flashed_messages() %}
  {% if messages %}
  {% for message in messages%}
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    {{message}}
  </div>
  {% endfor %}
  {% endif %}
  {% endwith %}
  <form class="text-left" action="" method="post">
    {{ form.hidden_tag() }}
    <h3 class="text-center pt-4">CREAR SEDE</h3>
    <div class="row mb-4 mb-lg-5">
      <!-- Form -->
      <div class="col-lg-4 col-sm-6">
        <div class="mb-4">
          <label>IdSede</label>
          <input type="text" class="form-control" id="IdSede" name="IdSede" readonly>
          
        </div>
      </div>
      <div class="col-lg-4 col-sm-6">
        <div class="mb-4">
          {{ form.NombreSede.label }}
          <input type="text" class="form-control" id="NombreSede" name="NombreSede">
          {% for error in form.NombreSede.errors %}
          <span style="color: red;">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="col-lg-4 col-sm-6">
        <div class="mb-4">
          {{ form.Direccion.label }}
          <input type="text" class="form-control" id="Direccion" name="Direccion">
          {% for error in form.Direccion.errors %}
          <span style="color: red;">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
    </div>

    <div class="row mb-4 mb-lg-5 pt-1">
      <div class="col-lg-4 col-sm-6">
        <div class="mb-4">
          {{ form.Telefono.label }}
          <input type="text" class="form-control" id="Telefono" name="Telefono">
          {% for error in form.Telefono.errors %}
          <span style="color: red;">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="col-lg-4 col-sm-6">
        <div class="mb-4">
          {{ form.Director.label }}
          <input type="text" class="form-control" id="Director" name="Director">
          {% for error in form.Director.errors %}
          <span style="color: red;">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="col-lg-4 col-sm-6">
        <div class="mb-3">
          {{ form.ActiveCampus.label }}
          <select class="form-select" id="ActiveCampus" name="ActiveCampus" aria-label="Default select example">
            <option selected>Seleccione el estado</option>
            <option value="Si">Activo</option>
            <option value="No">Inactivo</option>
          </select>
        </div>
      </div>
    </div>
    </div>
    <div class="col-lg-4 col-sm-6">
      <button class="btn btn-lg btn-primary" type="submit">Crear</button>
    </div>
  </form>
</div>
{% endblock %}

app/maestros/sede/templates/editCampus.html
{% extends "base_template.html" %}

{% block title %}Editar Sede{% endblock %}

{% block content %}
<div class="container pt-4">
  {% with messages=get_flashed_messages() %}
  {% if messages %}
  {% for message in messages%}
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    {{message}}
  </div>
  {% endfor %}
  {% endif %}
  {% endwith %}
  <form class="text-left" action="" method="post">
    {{ form.hidden_tag() }}
    <h3 class="text-center pt-4">CREAR SEDE</h3>
    <div class="row mb-4 mb-lg-5">
      <!-- Form -->
      <div class="col-lg-4 col-sm-6">
        <div class="mb-4">
          {{ form.IdSede.label }}
          <input type="text" class="form-control" id="IdSede" name="IdSede">
          {% for error in form.IdSede.errors %}
          <span style="color: red;">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="col-lg-4 col-sm-6">
        <div class="mb-4">
          {{ form.NombreSede.label }}
          <input type="text" class="form-control" id="NombreSede" name="NombreSede">
          {% for error in form.NombreSede.errors %}
          <span style="color: red;">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
    </div>

    <div class="row mb-4 mb-lg-5">
      <div class="col-lg-4 col-sm-6">
        <div class="mb-4">
          {{ form.Direccion.label }}
          <input type="text" class="form-control" id="Direccion" name="Direccion">
          {% for error in form.Direccion.errors %}
          <span style="color: red;">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
    </div>

    <div class="row mb-4 mb-lg-5 pt-1">
      <div class="col-lg-4 col-sm-6">
        <div class="mb-4">
          {{ form.Telefono.label }}
          <input type="text" class="form-control" id="Telefono" name="Telefono">
          {% for error in form.Telefono.errors %}
          <span style="color: red;">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="col-lg-4 col-sm-6">
        <div class="mb-4">
          {{ form.Ciudad.label }}
          <input type="text" class="form-control" id="Ciudad" name="Ciudad">
          {% for error in form.Ciudad.errors %}
          <span style="color: red;">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="col-lg-4 col-sm-6">
        <div class="mb-4">
          {{ form.Director.label }}
          <input type="text" class="form-control" id="Director" name="Director">
          {% for error in form.Director.errors %}
          <span style="color: red;">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="col-lg-4 col-sm-6">
        <div class="mb-3">
          {{ form.ActiveCampus.label }}
          <select class="form-select" id="ActiveCampus" name="ActiveCampus" aria-label="Default select example">
            <option selected>Seleccione el estado</option>
            <option value="Si">Activo</option>
            <option value="No">Inactivo</option>
          </select>
        </div>
      </div>
    </div>
    </div>
    <div class="col-lg-4 col-sm-6">
      <button class="btn btn-lg btn-primary" type="submit">Crear</button>
    </div>
  </form>
</div>
{% endblock %}

app/maestros/sede/templates/listCampus.html
{% extends "base_template.html" %}

{% block title %}Listado de Sedes{% endblock %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap5.css">

{% block content %}
<div class="list-employees container pt-4">
  {% with messages=get_flashed_messages() %}
  {% if messages %}
  {% for message in messages%}
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    {{message}}
  </div>
  {% endfor %}
  {% endif %}
  {% endwith %}
  <row>
    <h3 class='titular'>Sedes <a href="{{url_for('sede.createCampus')}}"><button class="btn btn-sm btn-primary"
      type="button">Nuevo</button></a></h3> 
  </row>
  <table class="table table-striped" id="data">
    <thead>
      <tr>
        <th>Id Sede</th>
        <th>Nombre Sede</th>
        <th>Dirección</th>
        <th>Teléfono</th>
        <th>Director</th>
        <th>Activo</th>
        <th>Acción</th>
      </tr>
    </thead>
    <tbody>
      {% for row in Datostabla %}
      <tr>
        <td>{{ row[0] }}</td>
        <td>{{ row[1] }}</td>
        <td>{{ row[2] }}</td>
        <td>{{ row[3] }}</td>
        <td>{{ row[4] }}</td>
        <td>{{ row[5] }}</td>
        <td>{{ row[6] }}</td>
        <td>{{ row[7] }}</td>
        <td>
          <a href="{{url_for('sede.editcampus',codigo=row[0])}}"><button class="btn btn-sm btn-primary"
              type="button">Editar</button></a>
          <a href="{{url_for('sede.deletecampus',codigo=row[0])}}"><button class="btn btn-sm btn-primary"
              type="button"
              onclick="return confirm('Estás seguro que deseas eliminar el registro?');">Eliminar</button></a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

</div>
<script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.js"></script>
<script type="text/javascript" charset="utf8"
  src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap5.js"></script>
<script>
  $(document).ready(function () {
    $('#data').DataTable({
      columns: [
        { orderable: true, searchable: false },
        { orderable: true, searchable: true },
        { orderable: true, searchable: true },
        { orderable: true, searchable: true },
        { orderable: true, searchable: true },
        { orderable: true, searchable: true },
        { orderable: true, searchable: true },
        { orderable: false, searchable: false }
      ],
    });
  });
</script>
{% endblock %}

app/maestros/sede/templates/seeEmployee.html
{% extends "base_template.html" %}

{% block title %}Ver Empleado{% endblock %}


{% block content %}
<div class="container pt-4">
  {% with messages=get_flashed_messages() %}
  {% if messages %}
  {% for message in messages%}
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    {{message}}
  </div>
  {% endfor %}
  {% endif %}
  {% endwith %}
  <form class="text-left" action="" method="post">
    <fieldset disabled>
      {{ form.hidden_tag() }}
      <h3 class="text-center pt-4">CONSULTAR EMPLEADO</h3>
      <div class="row mb-4 mb-lg-5">
        <!-- Form -->
        <div class="col-lg-4 col-sm-6">
          <div class="mb-3">
            {{ form.Tipodoc.label }}
            <select class="form-select" id="Tipodoc" name="Tipodoc" aria-label="Default select example">
              <option value="{{Datoregistro[0]}}">{{ Datoregistro[14] }}</option>
              <option value="RC">Registro civil</option>
              <option value="TI">Targeta de identidad</option>
              <option value="CC">Cédula de ciudadanía</option>
              <option value="CE">Cédula de extrangería</option>
            </select>
            {% for error in form.Tipodoc.errors %}
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
          </div>
        </div>

        <div class="col-lg-4 col-sm-6">
          <div class="mb-4">
            {{ form.Documento.label }}
            <input type="text" class="form-control" id="Documento" name="Documento" value="{{Datoregistro[1]}}">
            {% for error in form.Documento.errors %}
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
          </div>
        </div>
        <div class="col-lg-4 col-sm-6">
          <div class="mb-4">
            {{ form.Nombres.label }}
            <input type="text" class="form-control" id="Nombres" name="Nombres" value="{{Datoregistro[2]}}">
            {% for error in form.Nombres.errors %}
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
          </div>
        </div>
      </div>

      <div class="row mb-4 mb-lg-5">
        <div class="col-lg-4 col-sm-6">
          <div class="mb-4">
            {{ form.Apellidos.label }}
            <input type="text" class="form-control" id="Apellidos" name="Apellidos" value="{{Datoregistro[3]}}">
            {% for error in form.Apellidos.errors %}
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
          </div>
        </div>
        <div class="col-lg-4 col-sm-6">
          <div class="mb-3">
            {{ form.Genero.label }}
            <select class="form-select" id="Genero" name="Genero" aria-label="Default select example">
              <option value="{{Datoregistro[10]}}">{{ Datoregistro[15] }}</option>
              <option value="M">Masculino</option>
              <option value="F">Femenino</option>
            </select>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6">
          <!-- Form -->
          <div class="mb-4">
            {{ form.Nacimiento.label }}
            <input type="date" class="form-control" id="Nacimiento" name="Nacimiento" value="{{Datoregistro[11]}}">
            {% for error in form.Nacimiento.errors %}
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
          </div>
        </div>
      </div>

      <div class="row mb-4 mb-lg-5 pt-1">
        <div class="col-lg-4 col-sm-6">
          <div class="mb-4">
            {{ form.Email.label }}
            <input type="text" class="form-control" id="Email" name="Email" value="{{Datoregistro[13]}}">
            {% for error in form.Email.errors %}
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
          </div>
        </div>
        <div class="col-lg-4 col-sm-6">
          <div class="mb-4">
            {{ form.Telefono.label }}
            <input type="text" class="form-control" id="Telefono" name="Telefono" value="{{Datoregistro[4]}}">
            {% for error in form.Telefono.errors %}
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
          </div>
        </div>
        <div class="col-lg-4 col-sm-6">
          <div class="mb-4">
            {{ form.Direccion.label }}
            <input type="text" class="form-control" id="Direccion" name="Direccion" value="{{Datoregistro[12]}}">
            {% for error in form.Direccion.errors %}
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
          </div>
        </div>
      </div>

      <div class="row mb-4 mb-lg-5 pt-1">
        <div class="col-lg-4 col-sm-6">
          <div class="mb-4">
            {{ form.Contrasena.label }}
            <input type="password" class="form-control" id="Contrasena" name="Contrasena" value="********">
            {% for error in form.Contrasena.errors %}
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
          </div>
        </div>
        
        <div class="col-lg-4 col-sm-6">
          <div class="mb-3">
            {{ form.FieldEmployee.label }}
            <select class="form-select" id="FieldEmployee" name="FieldEmployee" aria-label="Default select example">
              <option value="{{Datoregistro[5]}}">{{ Datoregistro[6] }}</option>
              {% for row in sedes %}
              <option value="{{row[0]}}">{{row[1]}}</option>
              {% endfor %}
            </select>
          </div>
        </div>
      </div>

      <div class="row mb-4 mb-lg-5 pt-1">
        <div class="col-lg-4 col-sm-6">
          <div class="mb-3">
            {{ form.ActiveEmployee.label }}
            <select class="form-select" id="ActiveEmployee" name="ActiveEmployee" aria-label="Default select example">
              <option value="{{Datoregistro[9]}}">{{ Datoregistro[16] }}</option>
              <option value="Si">Activo</option>
              <option value="No">Inactivo</option>
            </select>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-sm-6">
      </div>
      <div class="col-lg-4 col-sm-6">
    </fieldset>
  </form>
</div>
<script>
  AttendantEmployee_select = document.getElementById('DataAcudiente');
</script>
{% endblock %}