app/maestros/categoria/models.py
from app.database import mysql
    
#CREATE
def crear_categoria(NombreCategoria):
    # Cursor para la ejecución
    cur = mysql.connection.cursor()  # Siempre va este
    # QUERY de Insert
    sQuery = '''INSERT INTO bd_escuela.categoria (Nom_Categoria) 
      VALUES(%s)'''
    # Ejecucion de la Sentencia
    cur.execute(sQuery, (NombreCategoria,))
    
    mysql.connection.commit()

#READ
#model para llenar la tabla de categorias
def datos_categoria():
    cur = mysql.connection.cursor()
    sQuery = '''SELECT * FROM bd_escuela.categoria '''.format()
    #print(sQuery)
    cur.execute(sQuery)
    row = cur.fetchall()

    # Ejecucion de la Sentencia
    cur.execute(sQuery)
    mysql.connection.commit()

    # Cerramos el cursor
    cur.close()

    return row

#model para traer los datos de un categoria en particular
def datos_categoria1(id):
    cur = mysql.connection.cursor()
    sQuery = '''SELECT * FROM bd_escuela.categoria where idCategoria like '%{}%' '''.format(id)
    #print(sQuery)
    cur.execute(sQuery)
    row = cur.fetchone()

    # Ejecucion de la Sentencia
    cur.execute(sQuery)
    mysql.connection.commit()

    # Cerramos el cursor
    cur.close()

    return row

#model para traer los datos de las categorias para seleccionar
def validar_categoria(IdCategoria):
    cur = mysql.connection.cursor()
    sQuery = "SELECT * FROM bd_escuela.categoria where idCategoria='{}' ".format(IdCategoria)
    #print(sQuery)
    cur.execute(sQuery)
    row = cur.fetchone()

    # Ejecucion de la Sentencia
    cur.execute(sQuery)
    mysql.connection.commit()

    # Cerramos el cursor
    cur.close()

    return row

#UPDATE
def actualizar_categoria(NombreCategoria, IdCategoria):
    # Cursor para la ejecución
    cur = mysql.connection.cursor()
    # QUERY de UPDATE
    # Ejecucion de la Sentencia
    cur.execute('''UPDATE bd_escuela.categoria SET Nom_Categoria=%s  WHERE Idcategoria=%s ''', (NombreCategoria, IdCategoria))
    mysql.connection.commit()

    # Cerramos el cursor
    cur.close()

#DELETE
def eliminar_categoria(IdCategoria):
    # Cursor para la ejecución
    cur = mysql.connection.cursor()
    # QUERY de UPDATE
    # Ejecucion de la Sentencia

    cur.execute('''DELETE from bd_escuela.categoria WHERE Idcategoria=%s ''', (IdCategoria,))
    mysql.connection.commit()

    # Cerramos el cursor
    cur.close()

app/maestros/categoria/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField,DateField, validators
from wtforms.validators import DataRequired, Email, Length

class Categories(FlaskForm):
    IdCategoria = StringField('Id categoría')
    NombreCategoria = StringField('Nombre de la categoría', validators=[
        DataRequired(
            message='El nombre de la categoría es obligatoria'
        ),
        Length(
            min=5,
            max=45,
            message='Mínimo 5 caratéres y máximo 45'
        )])

app/maestros/categoria/__init__.py
from flask import Blueprint

categoria = Blueprint('categoria',__name__, template_folder='templates',url_prefix='/categoria')

from . import routes

app/maestros/categoria/routes.py
from flask import render_template, request, redirect, url_for, flash, session
from .forms import Categories
from . import models
from werkzeug.security import generate_password_hash, check_password_hash
from . import categoria


#Ruta muestra la tabla de categorias
@categoria.route('/', methods=["GET", "POST"])
def list_categories():
    if 'documento' in session:
        row = models.datos_categoria()
        return render_template('listCategories.html', Datostabla=row)
    else:
        return redirect(url_for('inicio.login'))

#Ruta para crear registros
@categoria.route('/crear', methods=["GET", "POST"])
def createCategories():
    if 'documento' in session:
        if session['privilegio'] != 'C':
            form = Categories()
            
            if request.method == 'POST':
                if form.validate_on_submit():
                    IdCategoria = form.IdCategoria.data
                    NombreCategoria = form.NombreCategoria.data
                    # Validar que no exista el registro categoria
                    row = models.validar_categoria(IdCategoria)

                    if row == None:
                        # Se crea un nuevo registro en categoria
                        models.crear_categoria(NombreCategoria ,)
                        flash('Registro Creado Exitosamente', 'success')
                    else:
                        flash('El Registro ya existe', 'success')

                return redirect(url_for('categoria.list_categories'))
            else:
                return render_template('createCategories.html', form=form)
        else:
            flash('No dispone de privilegios para crear registros', 'success')
            return redirect(url_for('inicio.home'))
    else:
        return redirect(url_for('inicio.login'))
    
#Ruta para consultar registros
@categoria.route('/see/<int:codigo>', methods=["GET", "POST"])
def see_categories(codigo):
    if 'documento' in session:
            form = Categories()
            row = models.datos_categoria()
            return render_template('seeCategories.html', form=form, Datoregistro=row)
    else:
        return redirect(url_for('inicio.login'))

#Ruta para editar registros
@categoria.route('/edit/<int:codigo>', methods=["GET", "POST"])
def editcategories(codigo):
    if 'documento' in session:
            if session['privilegio'] != 'C':
                form = Categories()
                datos=models.datos_categoria1(codigo)
                if request.method == 'POST':
                    if form.validate_on_submit():
                        IdCategoria = form.IdCategoria.data
                        NombreCategoria = form. NombreCategoria.data
                        # Validar que no exista el registro categoria
                        models.actualizar_categoria(NombreCategoria , IdCategoria)
                        flash('Registro Actualizado Exitosamente', 'success')
                        return redirect(url_for('categoria.list_categories'))
                    else:
                        return render_template('editCategories.html', form=form, Datoregistro=datos)
                else:
                    return render_template('editCategories.html', form=form, Datoregistro=datos)
            else:
                flash('No dispone de privilegios para editar registros', 'success')
                return render_template('seeStudent.html', form=form, Datoregistro=datos)
    else:
        return redirect(url_for('inicio.login'))

#Ruta para eliminar registros
@categoria.route('/delete/<int:codigo>', methods=["GET", "POST"])
def deletecategories(codigo):
    if 'documento' in session:
            if session['privilegio'] != 'C':
                try:
                    models.eliminar_categoria(codigo)
                    flash('Registro Eliminado Exitosamente', 'success')
                except:
                    flash('El Registro no puede ser eliminado', 'success')
            else:
                flash('No dispone de privilegios para eliminar registros', 'success')
            return redirect(url_for('categoria.list_categories'))  
    else:
        return redirect(url_for('inicio.login'))

app/maestros/categoria/templates/createCategories.html
{% extends "base_template.html" %}

{% block title %}Crear Categorías{% endblock %}

{% block content %}
<div class="container pt-4">
  {% with messages=get_flashed_messages() %}
  {% if messages %}
  {% for message in messages%}
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    {{message}}
  </div>
  {% endfor %}
  {% endif %}
  {% endwith %}

  <form class="text-left" action="" method="post" novalidate>
    {{ form.hidden_tag() }}
    <h3 class="text-center pt-4">CREAR CATEGORÍAS</h3>
    <div class="row mb-4 mb-lg-5 pt-4">
      <div class="col-lg-4 col-sm-6">
        <div class="mb-4">
          {{ form.IdCategoria.label }}
          <input type="text" class="form-control" id="IdCategoria" name="IdCategoria" readonly>
          {% for error in form.IdCategoria.errors %}
          <span style="color: red;">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="col-lg-4 col-sm-6">
        <div class="mb-4">
          {{ form.NombreCategoria.label }}
          <input type="email" class="form-control" id="NombreCategoria" name="NombreCategoria">
          {% for error in form.NombreCategoria.errors %}
          <span style="color: red;">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
    </div>
    <div class="col-lg-4 col-sm-6">
      <button class="btn btn-lg btn-primary" type="submit">Crear categoría</button>
    </div>
    <div class="col-lg-4 col-sm-6">

    </div>
</div>
</form>
</div>
{% endblock %}

app/maestros/categoria/templates/editCategories.html
{% extends "base_template.html" %}

{% block title %}Editar Categorías{% endblock %}

{% block content %}
<div class="container pt-4">
  {% with messages=get_flashed_messages() %}
  {% if messages %}
  {% for message in messages%}
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    {{message}}
  </div>
  {% endfor %}
  {% endif %}
  {% endwith %}

  <form class="text-left" action="" method="post" novalidate>
    {{ form.hidden_tag() }}
    <h3 class="text-center pt-4">CREAR CATEGORÍAS</h3>
    <div class="row mb-4 mb-lg-5 pt-4">
      <div class="col-lg-4 col-sm-6">
        <div class="mb-4">
          {{ form.IdCategoria.label }}
          <input type="text" class="form-control" id="IdCategoria" name="IdCategoria" value="{{Datoregistro[0]}}" readonly>
          {% for error in form.IdCategoria.errors %}
          <span style="color: red;">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="col-lg-4 col-sm-6">
        <div class="mb-4">
          {{ form.NombreCategoria.label }}
          <input type="text" class="form-control" id="NombreCategoria" name="NombreCategoria" value="{{Datoregistro[1]}}" >
          {% for error in form.NombreCategoria.errors %}
          <span style="color: red;">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
    </div>
    <div class="col-lg-4 col-sm-6">
      <button class="btn btn-lg btn-primary" type="submit">Actualizar</button>
    </div>
    <div class="col-lg-4 col-sm-6">

    </div>
</div>
</form>
</div>
{% endblock %}

app/maestros/categoria/templates/listCategories.html
{% extends "base_template.html" %}

{% block title %}Listado de Categorías{% endblock %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap5.css">

{% block content %}
<div class="list-categories container pt-4">
  {% with messages=get_flashed_messages() %}
  {% if messages %}
  {% for message in messages%}
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    {{message}}
  </div>
  {% endfor %}
  {% endif %}
  {% endwith %}
  <row>
    <h3 class='titular'>Categoría <a href="{{url_for('categoria.createCategories')}}"><button class="btn btn-sm btn-primary"
      type="button">Nuevo</button></a></h3> 
  </row>
  <table class="table table-striped" id="data">
    <thead>
      <tr>
        <th>ID</th>
        <th>Nombre</th>
        <th>Acción</th>
      </tr>
    </thead>
    <tbody>
      {% for row in Datostabla %}
      <tr>
        <td>{{ row[0] }}</td>
        <td>{{ row[1] }}</td>
        <td>
          <a href="{{url_for('categoria.editcategories',codigo=row[0])}}"><button class="btn btn-sm btn-primary"
              type="button">Editar</button></a>
          <a href="{{url_for('categoria.deletecategories',codigo=row[0])}}"><button class="btn btn-sm btn-primary"
              type="button"
              onclick="return confirm('Estás seguro que deseas eliminar el registro?');">Eliminar</button></a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

</div>
<script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.js"></script>
<script type="text/javascript" charset="utf8"
  src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap5.js"></script>
<script>
  $(document).ready(function () {
    $('#data').DataTable({
      columns: [
        { orderable: true, searchable: false },
        { orderable: true, searchable: true },
        { orderable: false, searchable: false }
      ],
    });
  });
</script>
{% endblock %}